### ISSUE TITLE
badarith errors on CPUs with imprecise clocks

### ISSUE THREAD

**Issue by ferd** [folsom-project/folsom#19]
The two following code samples:

- https://github.com/folsom-project/folsom/blob/1a3d23ad1fa7a08a63700eb1d0327bc5c5206e05/src/folsom_metrics_meter.erl#L140-L144
- https://github.com/folsom-project/folsom/blob/1a3d23ad1fa7a08a63700eb1d0327bc5c5206e05/src/folsom_metrics_meter_reader.erl#L140-L144

Both looking like:

```erlang
calc_mean_rate(_, 0) ->
    0.0;
calc_mean_rate(Start, Count) ->
    Elapsed = folsom_utils:now_epoch_micro() - Start,
    Count / Elapsed.
```

Risks crashing on early calls after initialization on systems where the clock has low precision (i.e. milliseconds or larger at best). The calls to microseconds, if happening within the time interval as the one behind `Start`, will yield an `Elapsed` value of 0 and cause a failure.

This is unlikely to happen on most platforms since microseconds tend to span over time fast enough to never trigger this, but our Windows CI server appears to have triggered it repeatedly.

We're ready to patch this ourselves and then submit it, but we should make sure that the approach we take satisfies the project. Possibly:

```erlang
calc_mean_rate(_, 0) ->
    0.0;
calc_mean_rate(Start, Count) ->
    case folsom_utils:now_epoch_micro() - Start of
        0 -> 0.0;
        Elapsed -> Count / Elapsed
    end.
```
Which is not as accurate as 'infinity' but should not be absurdly bad in actual usage.

**Comment by jadeallenx** [comment]
This proposal seems pretty good. What do you think @joewilliams ?

**Comment by joewilliams** [comment]
@ferd @mrallen1 thanks for the ping, sorry missed this one, this seems reasonable to me. My only question is, does it make sense to fix this over in  `folsom_utils:now_epoch_micro` instead? Either way, I am happy to merge a PR that fixes this, please be sure to add a comment to explain the situation and test to verify both paths.

**Comment by ferd** [comment]
I'm not sure we could fix this in `now_epoch_micro` since it does not have the information about the relative time difference from `Start` to know that a 0 time difference is a problem?
