### ISSUE TITLE
can't build folsom

### ISSUE THREAD

**Issue by comtihon** [folsom-project/folsom#21]
https://hex.pm/packages/bear github links to https://github.com/project-folsom/bear
should be https://github.com/folsom-project/bear

**Comment by jadeallenx** [comment]
Ahh, good catch! Thanks.

**Comment by jadeallenx** [comment]
Will be fixed when https://github.com/folsom-project/bear/pull/8 gets merged.  

Are you having trouble building folsom as the ticket title implies? If so, how?

**Comment by comtihon** [comment]
I used my own build system [coon](https://github.com/comtihon/coon)
It uses hex api to get github http if url is not specified in config.

**Comment by puzza007** [comment]
https://github.com/folsom-project/bear/pull/8 has now been merged

**Comment by puzza007** [comment]
The correct link is now showing on hex.pm. This issue can be closed 👍
