### ISSUE TITLE
Compiler warnings for deprecated module random

### ISSUE THREAD

**Issue by ebengt** [folsom-project/folsom#26]
Greetings,

Very minor issue, but probably easily corrected.
I get these warnings when I compile folsom
_build/default/lib/folsom/src/folsom_sample_exdec.erl:67: Warning: random:uniform_s/2: the 'random' module is deprecated; use the 'rand' module instead
_build/default/lib/folsom/src/folsom_sample_exdec.erl:76: Warning: random:uniform_s/2: the 'random' module is deprecated; use the 'rand' module instead

_build/default/lib/folsom/src/folsom_sample_slide_uniform.erl:48: Warning: random:uniform_s/2: the 'random' module is deprecated; use the 'rand' module instead

_build/default/lib/folsom/src/folsom_sample_uniform.erl:52: Warning: random:uniform_s/2: the 'random' module is deprecated; use the 'rand' module instead

**Comment by joewilliams** [comment]
Thanks for the report! I would happily accept a PR for this fix.

**Comment by jadeallenx** [comment]
Is this with OTP 21? I think we just need to add 21 to the rebar.config due to #15

**Comment by ebengt** [comment]
I have OTP20. Would you want a backwards compatible solution (like http://erlang.org/doc/apps/erts/time_compat.erl <http://erlang.org/doc/apps/erts/time_compat.erl>) or just an upgrade ?

**Comment by jadeallenx** [comment]
I just compiled folsom using `rebar3 compile` on OTP 21 and 20, and there were no deprecation warnings about random. Are you compiling from the most recent version or using some alternate build system?

**Comment by ebengt** [comment]
I got folsom since my project depends on exometer. The rebar.config entry:
exometer_core/rebar.config:  {folsom, ".*", {git, "git://github.com/folsom-project/folsom <http://github.com/folsom-project/folsom>", {tag, "0.8.5"}}},

The installed folsom (in _build/default/lib/folsom) has a detached HEAD, but gitk says it is using 0.8.2. Not sure why the detached etc.

But, anyway, the warning I see is probably related to version 0.8.2, and I will try to persuade my project to become more modern. Somehow.

Sorry about the confusion.


bengt

**Comment by jadeallenx** [comment]
Sometimes I have to delete a dependency for rebar3 and remove the rebar3.lock file. You might want to see if the hash in the rebar.lock file points to the commit in your dependencies. (What you're describing sounds like a checkout due to rebar.lock)

**Comment by puzza007** [comment]
I've just verified that there are no deprecation warnings with OTP 22 on a fresh clone. I think this issue can safely be closed.
