### ISSUE TITLE
Hex.pm link 

### ISSUE THREAD

**Issue by ten0s** [folsom-project/folsom#28]
Please fix the link in [Hex.pm](https://hex.pm/packages/folsom/0.8.7), it incorrectly points to https://github.com/project-folsom/folsom

**Comment by joewilliams** [comment]
@puzza007 I think you have access to fix this, do you mind updating the link please?

**Comment by puzza007** [comment]
@joewilliams done. See merge req for code changes.

**Comment by joewilliams** [comment]
🙇 @puzza007 @ten0s
