### ISSUE TITLE
Amazing Atoms!

### ISSUE THREAD

**Issue by okeuday** [folsom-project/folsom#4]
I noticed the code https://github.com/folsom-project/folsom/blob/master/src/folsom_vm_metrics.erl#L283-L288 which should create an undefined number of atoms (potentially infinite) during the lifetime of the Erlang VM.  This should be a very bad thing indeed, since the space for atoms is limited and atoms are meant to be unique identifiers that are reused often.  Is there any reason why binaries can not be used here?

**Comment by jadeallenx** [comment]
@joewilliams Think this is something that should be addressed - would it be possible to use binaries here instead of atoms?
